"""
Project Euler Problem 2: even fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first  terms will be:
                1, 2, 3, 5, 8, 13, 21, 34, 55, 89 . . . . .

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


"""

# from utils.math_helper import *


def solve():
    # lazy approach -
    limit = 4_000_000
    a, b = 1, 2
    total_sum = 0

    while b < limit:
        if b % 2 == 0:
            total_sum += b
        a, b = b, a + b

    return total_sum


if __name__ == "__main__":
    ans = solve()
    print(ans)  # prints --> 4613732
