"""
Project Euler Problem 12 : Highly Divisible Triangular Number


    The sequence of triangle numbers is generated by adding the natural numbers.
    So the 7th triangle number would be 1+2+3+4+5+6+7=28.
    The first ten terms would be:
                    1,3,6,10,15,21,28,36,45,55,…

    Let us list the factors of the first seven triangle numbers:

                    1       :1
                    3       :1,3
                    6       :1,2,3,6
                    10      :1,2,5,10
                    15      :1,3,5,15
                    21      :1,3,7,21
                    28      :1,2,4,7,14,28

    We can see that 28 is the first triangle number to have over five divisors.

    What is the value of the first triangle number to have over five hundred divisors?


"""

# from utils.math_helper import *


def yeild_triangle_nos():
    n = 1
    triangle_no = 0
    while True:
        triangle_no += n
        yield triangle_no
        n += 1


def count_divisors(n):
    count = 0
    for i in range(1, int(n**0.5) + 1):
        if n % i == 0:
            count += 1 if i * i == n else 2
    return count


def solve():
    for triangle_no in yeild_triangle_nos():
        if count_divisors(triangle_no) > 500:
            return triangle_no


if __name__ == "__main__":
    print(solve())  # returns --> 76576500
